#!/bin/sh

# npm install -g forever
# sudo ln -s /usr/local/bin/node/bin/node /usr/bin/node
# in /etc/rc.lcal, add..
# sudo -u ec2-user /home/ec2-user/rrandom/serve

cd /home/ec2-user/rrandom

/usr/local/bin/node/bin/forever start server.js
